# Generated by Django 3.1.5 on 2021-01-28 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Sandwich',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamaño', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha Pedido')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendaSandwiche.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoSandwiche', models.CharField(default=None, max_length=50)),
                ('nombreI', models.CharField(default=None, max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, default=None, max_digits=5)),
                ('ingrediente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tiendaSandwiche.ingrediente')),
                ('pedido', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tiendaSandwiche.pedido')),
                ('sandwich', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tiendaSandwiche.sandwich')),
            ],
        ),
    ]
