# Generated by Django 3.1.5 on 2021-01-28 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaSandwiche', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='ingrediente',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tiendaSandwiche.ingrediente'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='nombreI',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='sandwich',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tiendaSandwiche.sandwich'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='tipoSandwiche',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
