# Generated by Django 3.1.5 on 2021-01-28 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaSandwiche', '0002_auto_20210127_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='precio',
        ),
        migrations.AddField(
            model_name='factura',
            name='precioI',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='precioS',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True),
        ),
    ]
