# Generated by Django 3.1.5 on 2021-01-28 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaSandwiche', '0003_auto_20210127_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoSandwich',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tiendaSandwiche.pedido')),
                ('sandwich', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tiendaSandwiche.sandwich')),
            ],
        ),
        migrations.CreateModel(
            name='SandwichIngredientePedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingrediente', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tiendaSandwiche.ingrediente')),
                ('pedido', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tiendaSandwiche.pedido')),
                ('sandwich', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tiendaSandwiche.sandwich')),
            ],
        ),
        migrations.DeleteModel(
            name='Factura',
        ),
    ]
